{% set version = '0.3.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmdformats
  version: {{ version|replace("-", "_") }}

source:
  fn: rmdformats_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rmdformats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rmdformats/rmdformats_{{ version }}.tar.gz
  sha256: 327f0bae3f5e0d4639074481a102607779aa216a8bda15967bbb1ae161cbde1a

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base=3.4.1=4
    - r-bookdown
    - r-htmltools
    - r-knitr
    - r-questionr
    - r-rmarkdown

  run:
    - r-base
    - r-bookdown
    - r-htmltools
    - r-knitr
    - r-questionr
    - r-rmarkdown

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rmdformats')"           # [not win]
    - "\"%R%\" -e \"library('rmdformats')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/juba/rmdformats
  license: GPL (>= 2)
  summary: HTML formats and templates for 'rmarkdown' documents, with some extra features such
    as automatic table of contents, lightboxed figures, dynamic crosstab helper.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: rmdformats
# Maintainer: Julien Barnier <julien.barnier@ens-lyon.fr>
# Authors@R: c(person("Julien", "Barnier", email="julien.barnier@ens-lyon.fr", role=c("aut","cre")))
# Version: 0.3.3
# Date: 2017-05-18
# License: GPL (>= 2)
# Encoding: UTF-8
# Title: HTML Output Formats and Templates for 'rmarkdown' Documents
# Description: HTML formats and templates for 'rmarkdown' documents, with some extra features such as automatic table of contents, lightboxed figures, dynamic crosstab helper.
# Imports: knitr, rmarkdown, bookdown, htmltools, questionr
# URL: https://github.com/juba/rmdformats
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2017-05-18 08:41:46 UTC; julien
# Author: Julien Barnier [aut, cre]
# Repository: CRAN
# Date/Publication: 2017-05-18 09:11:15 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
